In [4]:
 import numpy as np

In [10]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [18]:
c  = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
print(c[1][1])

5


In [25]:
# Create array of zeroes, Ones, Custom Array
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
b = np.ones((2, 3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
c = np.full((3, 2), 5)
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [35]:
d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
e = np.random.random((2, 3))
e

array([[0.40282644, 0.22400311, 0.06667455],
       [0.8986071 , 0.19369767, 0.34842758]])

In [59]:
e[1,0:3]

array([0.8986071 , 0.19369767, 0.34842758])

In [61]:
# Set some rows and columns with any values

In [65]:
z = np.zeros((3, 3))
print(z)
z[1, : ] = 5
z[ : , -1] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [67]:
print(z.dtype)

float64


In [69]:
# Change the dtype of a numpy array
array = np.zeros((2, 3), dtype = np.int64)

In [71]:
array

array([[0, 0, 0],
       [0, 0, 0]])

In [73]:
print(array.dtype)

int64


In [75]:
# Mathematical Operations on numpy

In [77]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6,],[7, 8]])

In [79]:
x+y

array([[ 6,  8],
       [10, 12]])

In [81]:
x*y

array([[ 5, 12],
       [21, 32]])

In [83]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [85]:
# Multiplication of Vectors
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print(a.dot(b))

30


In [87]:
print(np.sum(x))
print(np.sum(x, axis = 1))

10
[3 7]


In [101]:
# Stacking of arrays

a = np.array([1, 2, 3, 4])
b = a ** 2
print(np.stack((a,b), axis = 0))
print(np.stack((a,b), axis = 1))

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [103]:
a = np.stack((a,b), axis = 0)

In [107]:
a = a.reshape((4,2))

In [109]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 1,  4],
       [ 9, 16]])