In [2]:
# Numpy Random Module

# rand: Random values in a given shape
# randn: Return a sample(or samples) from the 'Standard Normal Distribution'
# randint: Return random integers from low(inclusive) to high(exclusive)
# random: return random floats in the half open interval [0.0, 1.0)
# choice: Generates a random sample from a givne 1-D array
# Shuffle: Shuffles the contents of a sequence

In [6]:
import numpy as np

In [66]:
np.random.seed(2)

In [82]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [88]:
np.random.seed(2) # psuedo random number generators
np.random.shuffle(a)
print(a)

[6 1 5 7 3 2 4 0 9 8]


In [80]:
a = np.random.rand(2,3)
print(a)

[[0.18508208 0.93154087 0.94773061]
 [0.4847491  0.32053644 0.15442667]]


In [40]:
a = np.random.randn(2,3)
print(a)

[[ 0.31005574  0.47839416 -0.16146673]
 [-0.0517933   0.72193252 -0.05037844]]


In [48]:
a = np.random.randint(5,10, 3)
print(a)

[8 9 8]


In [52]:
# Randomly pick one element form a array
element = np.random.choice([1, 2, 3, 4, 5, 6])
print(element)

4
