In [2]:
import numpy as np

In [4]:
# Some More Numpy Functions - Statistics
# min, max
# mean
# median
# average
# variance
# standard deviation

In [6]:
a = np.array([[1, 2, 3, 4], [7, 6, 2, 0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [12]:
np.mean(a, axis = 1)

array([2.5 , 3.75])

In [16]:
np.min(a, axis = 0)

array([1, 2, 2, 0])

In [18]:
np.mean(a)

3.125

In [20]:
b = a - 3.125

In [22]:
np.mean(b*b)

5.109375

In [28]:
np.var(a)

5.109375